---
branches:
- development
plugins:
- - "@semantic-release/commit-analyzer"
  - preset: conventionalcommits
- - "@semantic-release/release-notes-generator"
  - preset: conventionalcommits
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
    message: |-
      chore(release): ${nextRelease.version} [no ci]

      ${nextRelease.notes}
- - "@semantic-release/exec"
    publishCmd: |-
       ./bin/container_build.sh && \
       ./bin/container_publish.sh "Publish version ${nextRelease.version} at ${Date.now()}"
