FROM node:9.5-alpine

RUN apk update && \
    apk add --update --repository http://dl-3.alpinelinux.org/alpine/edge/testing vips-tools vips-dev fftw-dev gcc g++ make libc6-compat && \
    apk add git && \
    apk add python && \
    apk add openssh && \
    rm -rf /var/cache/apk/*

RUN npm install --global gatsby --no-optional gatsby@2.0
RUN npm install --global gh-pages --save-dev

COPY ./entry.sh /
RUN chmod +x /entry.sh
ENTRYPOINT ["/entry.sh"]
