#+TITLE: Hosting my own browser shell with v86 and buildroot
#+CREATED: <2022-10-14 Fri>
#+LAST_MODIFIED: [2022-10-20 Thu 21:38]
#+ROAM_TAGS: composition
#+OPTIONS: toc:nil
#+OPTIONS: tex:t
#+OPTIONS: _:nil ^:nil p:nil

#+HUGO_BASE_DIR: ./
#+hugo_front_matter_format: yaml
#+HUGO_CUSTOM_FRONT_MATTER: :date (org-to-blog-date (org-global-prop-value "CREATED"))
#+HUGO_CUSTOM_FRONT_MATTER: :hero ./images/hero.jpg
#+HUGO_CUSTOM_FRONT_MATTER: :secret true
#+HUGO_CUSTOM_FRONT_MATTER: :excerpt Beating word games one letter at a time

#+BEGIN_SRC emacs-lisp :exports none
  (defun org-hugo-link (link contents info) (org-md-link link contents info))

  ;; Setup org/latex exporting
  (add-to-list 'org-export-filter-latex-fragment-functions
               'sub-paren-for-dollar-sign)
  (add-to-list 'org-export-filter-headline-functions
               'remove-regexp-curly-braces)
  (add-to-list 'org-export-filter-latex-environment-functions
               'sub-paren-for-dollar-sign)
  (export-to-mdx-on-save)
#+END_SRC

#+RESULTS:
: Enabled mdx on save

Recently I rediscovered [[https://github.com/copy/v86][v86]] and wondered how hard it would be to "self host"
your own browser shell / OS.

So I gave it a try and am happy to release [[/shell][TAOA Shell]]!

Now to get the haters points out of the way:

1. This thing is pretty slow compared to bare metal (as any emulator is)
2. The OS is packaged poorly (hacked together over a week)

But these tradeoffs give us the benefits of:

1. Cheap hosting (all static assets)
2. Accessibility (just click a link)

Not only is tech cool in general, but actually has some unique practical
purposes. The main one I'm using it for is to self host my side projects
that aren't web based.

For example: in my last post I wrote about how to [[/posts/Writing-a-Weaver-solver][solve weaver]]. If people want
to use the script, they'd have to copy the code, download the weaver graph, and
run it. But now, with the click of a link, they can just try it in [[/shell][TAOA Shell]] to
see it in action.

For very little work of putting the script in TAOA Shell this tool becomes much
more accessible. This also generalizes beyond python scripts to anything that
can run in Linux (which is alot).

* 1. The OS

  Most personal hardware is powerful enough to run VMs / emulators at great
  speeds without any noticeable lag. Unfortunately
