FROM node:8.16.2-alpine3.10
RUN apk add \
  bash \
  libx11-dev \
  libxi \
  mesa-gl \
  autoconf \
  automake \
  bash \
  g++ \
  libc6-compat \
  libjpeg-turbo-dev \
  libpng-dev \
  make \
  nasm
